name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: ['3.9']

    steps:
      - name: STEP 1. Checkout repository
        uses: actions/checkout@v2

      - name: STEP 2. Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: STEP 3. Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel pytest
          brew install boost boost-python3

      - name: STEP 4. Build wheel
        run: |
          python setup.py v8
          python setup.py sdist bdist_wheel -d stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug
          sudo python setup.py install
          cp v8/out.gn/x64.release.sample/icudtl.dat stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug/icudtl.dat
        env:
          STPYV8_DEBUG: 1

      - name: STEP 5. Test wheel
        run: |
          pytest -v

      - name: STEP 6. Create wheel zip
        uses: vimtor/action-zip@v1
        with:
          files: stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug/
          recursive: false
          dest: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}-debug.zip

      - name: STEP 7. Upload wheel zip
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}-debug.zip
