name: Build Windows

on:
  workflow_dispatch:
  push:

jobs:
  build-v8:
    name: Build v8
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Build
        run: |
          python setup.py v8

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: v8_monolith.lib
          path: |
            v8\out.gn\x64.release.sample\obj\v8_monolith.lib

  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: ['3.10']

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2

      - name: STEP 1. Checkout repository
        uses: actions/checkout@v3

      - name: STEP 2. Set up Python
        id: install-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download Boost
        id: download-boost
        uses: suisei-cn/actions-download-file@v1.4.0
        with:
          url: https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.zip

      - name: Install Boost
        id: install-boost
        run: |
          $BOOST_ROOT="D:\boost"
          $INSTALL_LOG="install.log"
          mkdir $BOOST_ROOT
          Expand-Archive ${{ steps.download-boost.outputs.filename }} -DestinationPath $BOOST_ROOT
          cd $BOOST_ROOT\*
          echo "BOOST_ROOT=$pwd" >> $env:GITHUB_OUTPUT
          echo "BOOST_ROOT=$pwd" >> $env:GITHUB_ENV
          echo "BOOST_LIBRARYDIR=$pwd\stage\lib" >> $env:GITHUB_ENV

      - name: STEP 4. Build Boost.Python
        working-directory: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        run: |
          .\bootstrap.bat
          if (-not $?) { type bootstrap.log }
          $escapedPythonPath = "${{ steps.install-python.outputs.python-path }}" -Replace "\\","\\"
          echo "using python : : ""$escapedPythonPath"" ;" >> project-config.jam
          (Get-Content libs\python\src\exec.cpp).replace('_Py_fopen', 'fopen') | Set-Content libs\python\src\exec.cpp
          .\b2.exe stage link=static runtime-link=static --with-python --debug-configuration
          ls stage\lib

      - name: Download v8 artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: v8_monolith.lib

      - name: STEP 5. Build wheel
        env:
          DEPOT_TOOLS_WIN_TOOLCHAIN: 0
        run: |
          python -m pip freeze
          python -m pip show wheel
          python -m pip install -U setuptools
          python -m pip install wheel
          $env:LIB="$env:LIB;${{steps.download.outputs.download-path}};${{ steps.install-boost.outputs.BOOST_ROOT }}\stage\lib"
#          python setup.py v8
          python setup.py sdist bdist_wheel -d stpyv8-${{ matrix.os }}-${{ matrix.python-version }}
          python setup.py install
          cp v8/out.gn/x64.release.sample/icudtl.dat stpyv8-${{ matrix.os }}-${{ matrix.python-version }}/icudtl.dat

      - name: STEP 6. Test wheel
        run: |
          pytest -v

      - name: STEP 7. Create wheel zip
        uses: vimtor/action-zip@v1.1
        with:
          files: stpyv8-${{ matrix.os }}-${{ matrix.python-version }}/
          recursive: false
          dest: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}.zip

      # - name: STEP 7. Upload wheel zip
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: wheels
      #     path: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}.zip
