name: MacOSX build/release workflow

on:
  push:
  pull_request:
  release:
    types: [published]
    branches:
      - master

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13]
        python-version: ['3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools delocate wheel pytest pytest-order
          brew update
          brew install boost
          brew install boost-python3 --ignore-dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      - name: Build wheel
        run: |
          python setup.py v8
          python setup.py sdist bdist_wheel -d stpyv8-${{ matrix.os }}-${{ matrix.python-version }}

      - name: Repair wheel
        run: |
          delocate-wheel stpyv8-${{ matrix.os }}-${{ matrix.python-version }}/stpyv8*.whl

      - name: Uninstall boost
        run: |
          brew uninstall boost boost-python3

      - name: Install wheel
        run: |
          python -m pip install --find-links=stpyv8-${{ matrix.os }}-${{ matrix.python-version }} stpyv8

      - name: Test wheel
        run: |
          pytest -v

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name != 'release' }}
        with:
          name: stpyv8-${{ matrix.os }}-python${{ matrix.python-version }}
          path: stpyv8-${{ matrix.os }}-${{ matrix.python-version }}/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: stpyv8-${{ matrix.os }}-${{ matrix.python-version }}/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}
